enable-ssh-support
pinentry-program /usr/bin/pinentry-tty
default-cache-ttl 7200 # time (s) to keep vault open
max-cache-ttl 14400 # max time (s) to keep vault open
default-cache-ttl-ssh 7200
max-cache-ttl-ssh 14400
log-file /home/thomas/.gnupg/gpg-agent.log
debug-level basic
verbose
