enable-ssh-support
pinentry-program /usr/bin/pinentry-tty
default-cache-ttl 600 # time (s) to keep vault open
max-cache-ttl 3600 # max time (s) to keep vault open
log-file /home/thomas/.gnupg/gpg-agent.log
debug-level basic
verbose
