#!/usr/bin/env bash

PROJECTS_HOME=${PROJECTS_HOME:-$HOME/projects/}
PLAYGROUND_HOME=${PLAYGROUND_HOME:-$HOME/playground/}

if [[ ! -d $PROJECTS_HOME ]]; then
    echo "Path not found: $PROJECTS_HOME"
fi

if [[ $# -eq 1 ]]; then
    selected=$(find $1 -maxdepth 3 -type d | fzf)
else
    selected=$(
        # find "$PROJECTS_HOME" "$PLAYGROUND_HOME" \
        find "$HOME" \
             -mindepth 1 -maxdepth 6 \
             \( -name node_modules -o -name .git -o -name venv -o -name __pycache__ \) -prune \
             -o -type d -print | fzf
         )
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# OK - tmux is not running
if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    echo "Creating session"
    if ls -a $selected | grep -q '^.git$'; then
        tmux new-session -ds "$selected_name" -c "$selected"
        tmux send-keys -t "$selected_name" "nvim" C-m
    elif [[ "$selected_name" == *data || "$selected_name" == "reports" ]]; then
        tmux new-session -ds "$selected_name" -c "$selected" vd
    else
        tmux new-session -ds "$selected_name" -c "$selected"
    fi
fi

if [[ -z "$TMUX" ]]; then
    tmux a -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
