#!/usr/bin/env bash

if ! tmux has-session -t llm 2>/dev/null; then
  tmux new-session -d -s llm -n codex-mini -c "${PROJECTS_HOME:-/home/thomas/projects}" "zsh -i -c '$(which chatgpt)'"
  if [[ $? -eq 1 ]]; then
    echo "ERROR: Could not spawn tmux session."
    exit 1
  fi
fi

tmux switch-client -t llm
tmux select-window -t llm:codex-mini
