#!/usr/bin/env bash

if [[ -z $PROJECTS_HOME ]]; then
    echo "Please export PROJECTS_HOME first."
fi

if [[ $# -eq 1 ]]; then
    selected=$(find $1 -maxdepth 2 -type d | fzf)
else
    selected=$(find "$PROJECTS_HOME" "$PLAYGROUND_HOME" \
        -mindepth 1 -maxdepth 4 \
         \( -name node_modules -o -name .git -o -name venv -o -name __pycache__ \) -prune -o \
        -type d -print | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# OK - tmux is not running
if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected"
    exit 0
fi

# OK - tmux is running but client is not attached, session with selected_name does not exist
if [[ -z $TMUX ]] && ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -s $selected_name -c "$selected"
    tmux a -t $selected_name
    if ! [[ "$selected_name" == *data || "$selected_name" == "reports" ]]; then
        tmux send-keys -t $selected_name "nvim" ENTER
    else
        tmux send-keys -t $selected_name "vd" ENTER
    fi
    exit 0
fi

# OK - tmux is running but client is not attached, session with selected_name exists
if [[ -z $TMUX ]] && tmux has-session -t=$selected_name 2> /dev/null; then
    tmux a -t $selected_name
    exit 0
fi

# OK - tmux is running and client is attached, session with selected_name does not exist
if [[ ! -z $TMUX ]] && ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c "$selected"
    tmux switch-client -t $selected_name
    if ! [[ "$selected_name" == *data || "$selected_name" == "reports" ]]; then
        tmux send-keys -t $selected_name "nvim" ENTER
    else
        tmux send-keys -t $selected_name "vd" ENTER
    fi
    exit 0
fi

# OK - tmux is running and client is attached, session with selected_name exists
if [[ ! -z $TMUX ]] && tmux has-session -t=$selected_name 2> /dev/null; then
    tmux switch-client -t $selected_name
    exit 0
fi
