import = ["~/.config/alacritty/rose-pine.toml"]

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 16

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNerdFontMono"

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNerdFontMono"

[font.offset]
x = 0
y = 0

[mouse]
faux_scrolling_lines = 1
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_title = true
# startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

# [window.padding]
# x = 4
# y = 0
